#pragma once

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 100

#define USB_MAX_POWER_CONSUMPTION 100
#define OLED_BRIGHTNESS 128

#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_DISPLAY_128X64

#define I2C_SCL_PIN D0
#define I2C_SDA_PIN D1
